# Kafka 클러스터 정보
bootstrap.servers=kafka:29092

# Kafka Streams 애플리케이션 ID
application.id=user-event-streams-app

# 기본 key/value Serde (직렬화/역직렬화)
default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde

# 상태 저장소 위치 (로컬 디렉토리)
state.dir=/tmp/kafka-streams/user-event-streams

# 오프셋 자동 리셋 (earliest: 처음부터, latest: 최신부터)
auto.offset.reset=earliest

# 처리 보장 레벨 (exactly_once / at_least_once)
processing.guarantee=exactly_once_v2

# Slack 알림 설정
slack.webhook.url="your_slack_webhook_url"
slack.channel=#ecommerce-pipeline