# Python 버전
FROM python:3.9-slim

# 작업 디렉토리 생성
WORKDIR /app

# 필요한 패키지 설치
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc python3-dev netcat-openbsd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# requirements.txt 복사 및 설치
COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade six kafka-python
RUN pip install --no-cache-dir -r requirements.txt

COPY python_src/ /app/

# 로그, 플래그 폴더 생성
RUN mkdir -p /app/logs /app/flags

# 환경 변수 설정 (기본값)
ENV EVENT_ACTIVE_FLAG=/app/flags/event_active.flag
ENV PYTHONUNBUFFERED=1

# 컨테이너 시작 시 실행할 명령
CMD ["python", "main/main_save_purchase.py"]